# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Start Torque Sandbox
      id: start-sandbox
      uses: QualiTorque/torque-start-sb-action@v0.1.2
      with:
        space: qa-space1
        blueprint_name: provision-s3-buckets
        torque_token: ${{ secrets.MYTOKEN }}
        duration: 120
        timeout: 0
        # inputs: 'replicaCount=3'
        torque_url: "https://preview.qtorque.io"
    - name: Sleep Sandbox
      run: sleep 30
      
    - name: Stop sandbox
      uses: QualiTorque/torque-end-sb-action@v0.1.1
      with:
        space: qa-space1
        sandbox_id: ${{ steps.start-sandbox.outputs.sandbox_id }}
        torque_token: ${{ secrets.MYTOKEN }} 
        torque_url: "https://preview.qtorque.io"
      
